accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import UserLogin


app_name = 'accounts'

urlpatterns = [
    path('profile/myfollowers', views.myFollowers, name = 'myfollowers'),
    path('login/', views.loginUser, name = 'login'),
    path('logout/', views.logoutUser, name = 'logout'),
    path('register/', views.account_register, name = 'register'),
    path('profile/', views.profile, name ='profile'),
   
]

classroom/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('notes/', include('notebooks.urls', namespace='notes')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
   
]

notebooks/urls.py
from django.urls import path
from .views import NotesView, NotesDetailView, UpdateNotesView, CreateNotesView, DeleteNotesView, allNotes

app_name = 'notebooks'

urlpatterns = [
    path('', NotesView.as_view(), name='notebooks'),
    path('all_notes/', allNotes, name='all_notes'),
    path('<slug:slug>/', NotesDetailView.as_view(), name='note-detail'),
    path('create', CreateNotesView.as_view(), name='create-note'),
    # path('<pk>/dislike', DisLike.as_view(), name='dislike'),
    # path('<pk>/like', AddLike.as_view(), name='like'),
    path('<int:pk>/update', UpdateNotesView.as_view(), name='update'),
    path('<pk>/delete', DeleteNotesView.as_view(), name='delete'),
   
]

templates/base/authBase.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static '/css/main.css' %}">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static '/css/login.css' %}">

    <script src="{% static '/js/main.js' %}"></script>
    <script src="{% static '/js/register.js' %}"></script>
    <title>{% block title %}{% endblock title %}</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'notes:notebooks' %}">List of Notes</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'notes:notebooks' %}">Home</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>

    {% block scripts %}
    {% endblock scripts %}


    {% block content %}

    {% endblock content %}

</body>

</html>

templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"></script>
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.css" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <link rel="stylesheet" type="text/css" media="screen" href="{% static '/css/main.css' %}">
  <script src="{% static '/js/main.js' %}"></script>
  <title>{% block title %}{% endblock title %}</title>
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'accounts:profile' %}">Dashboard</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'notes:notebooks' %}">My Notes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'notes:all_notes' %}">Classmate's Notes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'notes:create-note' %}">Start A New Note</a>
          </li>
        </ul>
        <form class="d-flex">

          <div class="container btn btn-outline-light mr-2">Welcome back <strong> {{ user.username}}</strong>
          </div>
          <button class="btn btn-outline-light"><a href="{% url 'accounts:logout' %}">Logout</a></button>
        </form>
      </div>
    </div>
  </nav>

  {% block scripts %}
  {% endblock scripts %}


  {% block content %}

  {% endblock content %}

</body>

</html>